spring:
  kafka:
    bootstrap-servers: localhost:29092

  data:
    cassandra:
      contact-points: 192.168.68.53
      port: 9042
      keyspace-name: orders
      username: cassandra
      password: cassandra